name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        node: ['14', '16']
    name: Build node v${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: package.json
      - run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Report coverage
        run: npm run codecov
        if: ${{ matrix.node == '14' }} # codecov for node 16 fails atm
